export type TGenre =
  | 'POP'
  | 'HIP_HOP_RAP'
  | 'DANCE'
  | 'ELECTRONIC'
  | 'SOUL_RNB'
  | 'ALTERNATIVE'
  | 'ROCK'
  | 'LATIN'
  | 'FILM_TV'
  | 'COUNTRY '
  | 'WORLDWIDE '
  | 'REGGAE_DANCE_HALL'
  | 'HOUSE '
  | 'K_POP'
